import 'package:equatable/equatable.dart';
import '../models/learning_signal.dart';
import '../models/recommendation.dart';
import 'difficulty_engine.dart';

/// Strongly-typed category of learning recommendation generated by Adventure Brain.
enum LearningRecommendationType {
  introduceNewVocabulary,
  reviewWeakVocabulary,
  reviewDueVocabulary,
  continueWorld,
  replayGame,
  practiceListening,
  practiceSpeaking,
  readStory,
  comprehensionPractice,
  confidenceActivity,
  mixedRevision,
}

extension LearningRecommendationTypeExtension on LearningRecommendationType {
  String get displayName {
    switch (this) {
      case LearningRecommendationType.introduceNewVocabulary:
        return 'New Word Discovery';
      case LearningRecommendationType.reviewWeakVocabulary:
        return 'Reinforce Tricky Words';
      case LearningRecommendationType.reviewDueVocabulary:
        return 'Spaced Memory Review';
      case LearningRecommendationType.continueWorld:
        return 'Continue Adventure Trail';
      case LearningRecommendationType.replayGame:
        return 'Replay Favorite Game';
      case LearningRecommendationType.practiceListening:
        return 'Listening Practice';
      case LearningRecommendationType.practiceSpeaking:
        return 'Speaking Practice';
      case LearningRecommendationType.readStory:
        return 'Picture Book Story';
      case LearningRecommendationType.comprehensionPractice:
        return 'Story Comprehension';
      case LearningRecommendationType.confidenceActivity:
        return 'Confidence Boost Play';
      case LearningRecommendationType.mixedRevision:
        return 'Mixed Adventure Review';
    }
  }
}

/// Explainable, pedagogical recommendation produced by the Adventure Brain.
///
/// Contains both an [internalReason] (transparent for parents, analytics, and debugging)
/// and a [childFriendlyPrompt] (warm, playful spoken dialogue from Pip).
class LearningRecommendation extends Equatable {
  final String childId;
  final LearningRecommendationType type;
  final List<String> targetVocabularyIds;
  final String worldId;
  final String lessonId;
  final String activityId;
  final String internalReason;
  final String childFriendlyPrompt;
  final int priorityScore; // 1 (lowest) to 100 (critical intervention)
  final AdaptiveDifficultyTier difficultyTier;
  final DateTime generatedAt;
  final String routePath;
  final String title;
  final String subtitle;

  const LearningRecommendation({
    required this.childId,
    required this.type,
    this.targetVocabularyIds = const [],
    required this.worldId,
    this.lessonId = '',
    required this.activityId,
    required this.internalReason,
    required this.childFriendlyPrompt,
    this.priorityScore = 50,
    this.difficultyTier = AdaptiveDifficultyTier.standard,
    required this.generatedAt,
    required this.routePath,
    required this.title,
    required this.subtitle,
  });

  /// Converts this [LearningRecommendation] to a legacy [Recommendation] for backward compatibility.
  Recommendation toLegacyRecommendation() {
    final SkillType legacySkill;
    switch (type) {
      case LearningRecommendationType.practiceListening:
        legacySkill = SkillType.listening;
        break;
      case LearningRecommendationType.practiceSpeaking:
        legacySkill = SkillType.speaking;
        break;
      case LearningRecommendationType.readStory:
      case LearningRecommendationType.comprehensionPractice:
        legacySkill = SkillType.reading;
        break;
      default:
        legacySkill = SkillType.vocabulary;
    }

    return Recommendation(
      activityId: activityId,
      activityType: type.name,
      worldId: worldId,
      skill: legacySkill,
      reason: internalReason,
      childFriendlyPrompt: childFriendlyPrompt,
      priority: priorityScore >= 90
          ? RecommendationPriority.criticalWeakness
          : priorityScore >= 80
              ? RecommendationPriority.overdueReview
              : RecommendationPriority.curriculumProgression,
      difficultyLevel: difficultyTier.index + 1,
      isReview: type == LearningRecommendationType.reviewDueVocabulary ||
          type == LearningRecommendationType.reviewWeakVocabulary ||
          type == LearningRecommendationType.mixedRevision,
      title: title,
      subtitle: subtitle,
      routePath: routePath,
    );
  }

  @override
  List<Object?> get props => [
        childId,
        type,
        targetVocabularyIds,
        worldId,
        lessonId,
        activityId,
        internalReason,
        childFriendlyPrompt,
        priorityScore,
        difficultyTier,
        generatedAt,
        routePath,
        title,
        subtitle,
      ];
}
