import 'package:equatable/equatable.dart';
import 'learning_signal.dart';
import 'recommendation.dart';

/// A balanced daily learning session generated by the Daily Adventure Planner.
class LearningSession extends Equatable {
  final String id;
  final String childId;
  final DateTime createdAt;
  final int totalEstimatedMinutes;
  final List<Recommendation> activities;
  final List<String> completedActivityIds;
  final SkillType primaryFocusSkill;
  final String primaryFocusValue;
  final int difficultyLevel;
  final bool isCompleted;

  const LearningSession({
    required this.id,
    required this.childId,
    required this.createdAt,
    required this.totalEstimatedMinutes,
    required this.activities,
    this.completedActivityIds = const [],
    required this.primaryFocusSkill,
    required this.primaryFocusValue,
    this.difficultyLevel = 1,
    this.isCompleted = false,
  });

  Recommendation? get nextActivity {
    for (final act in activities) {
      if (!completedActivityIds.contains(act.activityId)) {
        return act;
      }
    }
    return activities.isNotEmpty ? activities.first : null;
  }

  int get completedCount => completedActivityIds.length;
  int get totalCount => activities.length;
  double get progressPercentage => totalCount > 0 ? completedCount / totalCount : 0.0;

  LearningSession copyWith({
    String? id,
    String? childId,
    DateTime? createdAt,
    int? totalEstimatedMinutes,
    List<Recommendation>? activities,
    List<String>? completedActivityIds,
    SkillType? primaryFocusSkill,
    String? primaryFocusValue,
    int? difficultyLevel,
    bool? isCompleted,
  }) {
    return LearningSession(
      id: id ?? this.id,
      childId: childId ?? this.childId,
      createdAt: createdAt ?? this.createdAt,
      totalEstimatedMinutes: totalEstimatedMinutes ?? this.totalEstimatedMinutes,
      activities: activities ?? this.activities,
      completedActivityIds: completedActivityIds ?? this.completedActivityIds,
      primaryFocusSkill: primaryFocusSkill ?? this.primaryFocusSkill,
      primaryFocusValue: primaryFocusValue ?? this.primaryFocusValue,
      difficultyLevel: difficultyLevel ?? this.difficultyLevel,
      isCompleted: isCompleted ?? this.isCompleted,
    );
  }

  Map<String, dynamic> toJson() => {
        'id': id,
        'childId': childId,
        'createdAt': createdAt.toIso8601String(),
        'totalEstimatedMinutes': totalEstimatedMinutes,
        'activities': activities.map((e) => e.toJson()).toList(),
        'completedActivityIds': completedActivityIds,
        'primaryFocusSkill': primaryFocusSkill.name,
        'primaryFocusValue': primaryFocusValue,
        'difficultyLevel': difficultyLevel,
        'isCompleted': isCompleted,
      };

  factory LearningSession.fromJson(Map<String, dynamic> json) => LearningSession(
        id: json['id'] as String,
        childId: json['childId'] as String,
        createdAt: DateTime.parse(json['createdAt'] as String),
        totalEstimatedMinutes: json['totalEstimatedMinutes'] as int? ?? 15,
        activities: (json['activities'] as List<dynamic>?)
                ?.map((e) => Recommendation.fromJson(e as Map<String, dynamic>))
                .toList() ??
            const [],
        completedActivityIds: (json['completedActivityIds'] as List<dynamic>?)
                ?.map((e) => e as String)
                .toList() ??
            const [],
        primaryFocusSkill: SkillType.values.firstWhere(
          (e) => e.name == json['primaryFocusSkill'],
          orElse: () => SkillType.vocabulary,
        ),
        primaryFocusValue: json['primaryFocusValue'] as String? ?? 'Kindness',
        difficultyLevel: json['difficultyLevel'] as int? ?? 1,
        isCompleted: json['isCompleted'] as bool? ?? false,
      );

  @override
  List<Object?> get props => [
        id,
        childId,
        createdAt,
        totalEstimatedMinutes,
        activities,
        completedActivityIds,
        primaryFocusSkill,
        primaryFocusValue,
        difficultyLevel,
        isCompleted,
      ];
}
