import 'package:equatable/equatable.dart';
import 'learning_signal.dart';

/// Recommendation priority level (1 = Highest, 8 = Lowest).
enum RecommendationPriority {
  parentSafety(1),
  overdueReview(2),
  criticalWeakness(3),
  weakSkill(4),
  curriculumProgression(5),
  balancedPractice(6),
  newExploration(7),
  bonusContent(8);

  final int rank;
  const RecommendationPriority(this.rank);
}

/// A deterministic recommendation generated by the Adventure Brain.
class Recommendation extends Equatable {
  final String activityId;
  final String activityType; // 'vocab', 'game', 'grammar', 'story', 'speaking', 'review', 'challenge'
  final String worldId;
  final SkillType skill;
  final String reason; // Pedagogical explanation for parents / diagnostics
  final String childFriendlyPrompt; // Friendly, encouraging copy for the child
  final RecommendationPriority priority;
  final int estimatedDurationMinutes;
  final int difficultyLevel; // 1 to 5
  final String? valueConnectionId;
  final String? valueTitle;
  final bool isReview;
  final bool isRequired;
  final String title;
  final String subtitle;
  final String routePath;

  const Recommendation({
    required this.activityId,
    required this.activityType,
    required this.worldId,
    required this.skill,
    required this.reason,
    required this.childFriendlyPrompt,
    this.priority = RecommendationPriority.curriculumProgression,
    this.estimatedDurationMinutes = 4,
    this.difficultyLevel = 1,
    this.valueConnectionId,
    this.valueTitle,
    this.isReview = false,
    this.isRequired = false,
    required this.title,
    required this.subtitle,
    required this.routePath,
  });

  Map<String, dynamic> toJson() => {
        'activityId': activityId,
        'activityType': activityType,
        'worldId': worldId,
        'skill': skill.name,
        'reason': reason,
        'childFriendlyPrompt': childFriendlyPrompt,
        'priority': priority.name,
        'estimatedDurationMinutes': estimatedDurationMinutes,
        'difficultyLevel': difficultyLevel,
        'valueConnectionId': valueConnectionId,
        'valueTitle': valueTitle,
        'isReview': isReview,
        'isRequired': isRequired,
        'title': title,
        'subtitle': subtitle,
        'routePath': routePath,
      };

  factory Recommendation.fromJson(Map<String, dynamic> json) => Recommendation(
        activityId: json['activityId'] as String,
        activityType: json['activityType'] as String,
        worldId: json['worldId'] as String,
        skill: SkillType.values.firstWhere(
          (e) => e.name == json['skill'],
          orElse: () => SkillType.vocabulary,
        ),
        reason: json['reason'] as String,
        childFriendlyPrompt: json['childFriendlyPrompt'] as String,
        priority: RecommendationPriority.values.firstWhere(
          (e) => e.name == json['priority'],
          orElse: () => RecommendationPriority.curriculumProgression,
        ),
        estimatedDurationMinutes: json['estimatedDurationMinutes'] as int? ?? 4,
        difficultyLevel: json['difficultyLevel'] as int? ?? 1,
        valueConnectionId: json['valueConnectionId'] as String?,
        valueTitle: json['valueTitle'] as String?,
        isReview: json['isReview'] as bool? ?? false,
        isRequired: json['isRequired'] as bool? ?? false,
        title: json['title'] as String,
        subtitle: json['subtitle'] as String,
        routePath: json['routePath'] as String,
      );

  @override
  List<Object?> get props => [
        activityId,
        activityType,
        worldId,
        skill,
        reason,
        childFriendlyPrompt,
        priority,
        estimatedDurationMinutes,
        difficultyLevel,
        valueConnectionId,
        valueTitle,
        isReview,
        isRequired,
        title,
        subtitle,
        routePath,
      ];
}
