import 'package:kids_english_adventure/features/ai_tutor/domain/models/ai_curriculum_context.dart';
import 'package:kids_english_adventure/features/ai_tutor/domain/models/ai_mode.dart';
import 'ai_conversation_state_machine.dart';

/// Structured response generated by the scripted fallback engine.
class ScriptedTurnResponse {
  final String text;
  final String expressionEmoji;
  final List<String> suggestedReplies;
  final double accuracyScore;
  final bool isTargetMastered;
  final ConversationState nextState;

  const ScriptedTurnResponse({
    required this.text,
    this.expressionEmoji = '😊',
    this.suggestedReplies = const [],
    required this.accuracyScore,
    this.isTargetMastered = false,
    this.nextState = ConversationState.feedback,
  });
}

/// Rich, deterministic scripted dialogue engine ensuring an engaging, educational offline/fallback experience.
class ScriptedDialogueEngine {
  /// Generates the initial opening prompt for any AI mode.
  static ScriptedTurnResponse getInitialPrompt(AiCurriculumContext context) {
    final vocabWord = context.targetVocabulary.isNotEmpty ? context.targetVocabulary.first : 'adventure';

    switch (context.mode) {
      case AiMode.vocabularyTalk:
        return ScriptedTurnResponse(
          text: "Hello! I am Pip! 🦜 What is your favorite $vocabWord?",
          expressionEmoji: '😊',
          suggestedReplies: context.targetVocabulary.map((v) => "I like $v").toList(),
          accuracyScore: 1.0,
          nextState: ConversationState.prompt,
        );

      case AiMode.grammarTalk:
        final pattern = context.targetGrammar ?? "is / are";
        return ScriptedTurnResponse(
          text: "Let's build a great sentence with $pattern! Fill in the blank: The cat ___ small.",
          expressionEmoji: '✍️',
          suggestedReplies: const ['is', 'are'],
          accuracyScore: 1.0,
          nextState: ConversationState.prompt,
        );

      case AiMode.dailyEnglish:
        return ScriptedTurnResponse(
          text: "Assalamu Alaikum! ☀️ How is the weather outside your window today?",
          expressionEmoji: '☀️',
          suggestedReplies: const ['It is sunny ☀️', 'It is rainy 🌧️', 'It is cloudy ☁️'],
          accuracyScore: 1.0,
          nextState: ConversationState.prompt,
        );

      case AiMode.storyTalk:
        final title = context.storyTitle ?? "our story";
        return ScriptedTurnResponse(
          text: "Let's talk about $title! 📖 Who was your favorite friend in the story?",
          expressionEmoji: '📖',
          suggestedReplies: context.targetVocabulary.isNotEmpty
              ? context.targetVocabulary.take(3).toList()
              : const ['The kitten 🐱', 'The elephant 🐘', 'The teacher 👨‍🏫'],
          accuracyScore: 1.0,
          nextState: ConversationState.prompt,
        );

      case AiMode.mannersTalk:
        return ScriptedTurnResponse(
          text: "Pip gives you a colorful pencil! ✏️ What polite words do you say?",
          expressionEmoji: '🤲',
          suggestedReplies: const ['Thank you! 😊', 'JazakAllah Khair! 🌟', 'Alhamdulillah! 🤲'],
          accuracyScore: 1.0,
          nextState: ConversationState.prompt,
        );

      case AiMode.speakingChallenge:
        final sentence = context.targetGrammar ?? "The sun is bright and warm today.";
        return ScriptedTurnResponse(
          text: "Speaking Challenge! 🎙️ Tap the mic and say: \"$sentence\"",
          expressionEmoji: '🎙️',
          suggestedReplies: [sentence],
          accuracyScore: 1.0,
          nextState: ConversationState.prompt,
        );

      case AiMode.reviewTalk:
        final weakness = context.weaknessTarget ?? vocabWord;
        return ScriptedTurnResponse(
          text: "Let's do a quick power review on $weakness! 🧠 Can you say: \"I see a $vocabWord\"?",
          expressionEmoji: '🧠',
          suggestedReplies: ["I see a $vocabWord", "Yes, $vocabWord"],
          accuracyScore: 1.0,
          nextState: ConversationState.prompt,
        );
    }
  }

  /// Processes child turn and generates a curriculum-guided scripted response.
  static ScriptedTurnResponse processTurn({
    required String childInput,
    required AiCurriculumContext context,
    required int turnIndex,
    required ConversationState currentState,
  }) {
    final lower = childInput.toLowerCase();
    final vocabWord = context.targetVocabulary.isNotEmpty ? context.targetVocabulary[turnIndex % context.targetVocabulary.length] : 'word';

    // 1. Evaluate accuracy against target vocabulary or grammar
    bool isMatch = false;
    for (final v in context.targetVocabulary) {
      if (lower.contains(v.toLowerCase())) {
        isMatch = true;
        break;
      }
    }
    if (lower.contains('is') || lower.contains('thank') || lower.contains('sunny') || lower.contains('rainy')) {
      isMatch = true;
    }

    final double score = isMatch ? 0.95 : 0.65;

    // 2. Generate progressive response
    switch (context.mode) {
      case AiMode.vocabularyTalk:
        if (isMatch) {
          return ScriptedTurnResponse(
            text: "Awesome! $vocabWord is great! 🌟 Can you tell me what color it is?",
            expressionEmoji: '⭐',
            suggestedReplies: ["It is green 🌿", "It is yellow 💛", "It is big 🐘"],
            accuracyScore: score,
            isTargetMastered: true,
            nextState: ConversationState.success,
          );
        } else {
          return ScriptedTurnResponse(
            text: "Good try! 🎈 Let's say together: \"I like $vocabWord\"!",
            expressionEmoji: '😊',
            suggestedReplies: ["I like $vocabWord"],
            accuracyScore: score,
            nextState: ConversationState.scaffold,
          );
        }

      case AiMode.grammarTalk:
        if (lower.contains('is')) {
          return const ScriptedTurnResponse(
            text: "Spot on! \"The cat IS small.\" 🌟 Singular things use 'is'!",
            expressionEmoji: '⭐',
            suggestedReplies: ['The birds ARE singing 🐦', 'The cat IS happy 🐱'],
            accuracyScore: 0.95,
            isTargetMastered: true,
            nextState: ConversationState.success,
          );
        } else {
          return const ScriptedTurnResponse(
            text: "Remember: One cat uses 'is'! Say: \"The cat is small\" ✍️",
            expressionEmoji: '🤔',
            suggestedReplies: ['The cat is small'],
            accuracyScore: 0.60,
            nextState: ConversationState.scaffold,
          );
        }

      case AiMode.mannersTalk:
        if (lower.contains('thank') || lower.contains('jazak')) {
          return const ScriptedTurnResponse(
            text: "MashaAllah! That is so kind and polite! Saying thank you brings joy! 🤲💖",
            expressionEmoji: '🤲',
            suggestedReplies: ['Alhamdulillah 🌟', 'Sharing is caring 🍎'],
            accuracyScore: 1.0,
            isTargetMastered: true,
            nextState: ConversationState.success,
          );
        } else {
          return const ScriptedTurnResponse(
            text: "When someone shares with us, we say: \"Thank you!\" or \"JazakAllah Khair!\" 😊",
            expressionEmoji: '😊',
            suggestedReplies: ['Thank you! 😊', 'JazakAllah Khair! 🌟'],
            accuracyScore: 0.70,
            nextState: ConversationState.scaffold,
          );
        }

      case AiMode.storyTalk:
        return ScriptedTurnResponse(
          text: "Wonderful! We learned that being kind to animals is loved by Allah! 🌟",
          expressionEmoji: '📖',
          suggestedReplies: ['I love helping animals 🐱', 'Let us be kind 🤲'],
          accuracyScore: score,
          isTargetMastered: true,
          nextState: ConversationState.success,
        );

      case AiMode.speakingChallenge:
        return ScriptedTurnResponse(
          text: isMatch ? "Super speaking! Clear, loud, and confident! 🎙️⭐" : "Great effort speaking! Practice makes perfect! 🌟",
          expressionEmoji: '🎙️',
          suggestedReplies: ["I love English! 🌟"],
          accuracyScore: score,
          isTargetMastered: isMatch,
          nextState: isMatch ? ConversationState.success : ConversationState.retry,
        );

      case AiMode.reviewTalk:
        return ScriptedTurnResponse(
          text: "Brilliant review work! Your brain memory is getting super strong! 🧠⚡",
          expressionEmoji: '🧠',
          suggestedReplies: ["I mastered it! ⭐"],
          accuracyScore: score,
          isTargetMastered: true,
          nextState: ConversationState.complete,
        );

      case AiMode.dailyEnglish:
        return ScriptedTurnResponse(
          text: "SubhanAllah! What a wonderful day to learn together in our English world! ☀️🌿",
          expressionEmoji: '😊',
          suggestedReplies: ['Alhamdulillah! 🌟', 'Let us play! 🚀'],
          accuracyScore: score,
          isTargetMastered: true,
          nextState: ConversationState.success,
        );
    }
  }
}
